[workspace]
changelog_update = true
semver_check = true
dependencies_update = true
git_release_enable = true

[[package]]
name = "temps-core"
version_group = "core"

[[package]]
name = "temps-chrono"

[[package]]
name = "temps-jiff"

[[package]]
name = "temps"

[[package]]
name = "temps-testhelpers"
version_group = "core"
