[package]
name = "temps-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Core functionality for temps - time and date parsing library"
authors.workspace = true
repository.workspace = true
readme = "../README.md"
license.workspace = true

[dependencies]
chumsky = "=0.13.0"
ariadne = "=0.6.0"
thiserror = "=2.0.20"

[dev-dependencies]
mockall = "=0.15.0"
temps-testhelpers = { path = "../temps-testhelpers" }
