on:
  push:
    tags:
      - "temps-v*"

name: Release "temps-macros" and "temps"
jobs:
  build:
    name: Release (crates.io & github.com)
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - run: cargo login ${CARGO_RELEASE_TOKEN}
        env:
          CARGO_RELEASE_TOKEN: ${{ secrets.CARGO_RELEASE_TOKEN }}
      - run: cargo publish -p temps-macros
      - run: sleep 10
      - run: cargo update --dry-run
      - run: cargo publish -p temps

