on:
  push:
    tags:
      - "temps-v*"
  workflow_run:
    workflows: [Release "temps-macros"]
    types:
      - completed

name: Release "temps"
jobs:
  build:
    name: Release (crates.io & github.com)
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - run: cargo login ${CARGO_RELEASE_TOKEN}
        env:
          CARGO_RELEASE_TOKEN: ${{ secrets.CARGO_RELEASE_TOKEN }}
      - run: cargo publish -p temps

